[tool.poetry]
name = "django-demo-reversion-roles"
version = "0.1.0"
description = ""
authors = ["David Kwast"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "<5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
